name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
    NODE_VERSION: '12.x'  # set this to the node version to use

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: 
      contents: write
      packages: write 

    steps:
    - name: Add SHORT_SHA env property with commit short sha      
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-6`" >> $GITHUB_ENV
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install and build
      run: |
        echo '{"version": "${{SHORT_SHA}}"}' > src/version.json
        cat src/version.json
        npm install 
        npm run build --if-present
      env:
         CI: false

